### PR TITLE
new request

### PR DESCRIPTION
**Pull request by goodtaeeun**
Hey

### CODE REVIEW

**Comment by Ahn-Ssu** [comment]
plz add your name and student ID

**Comment by goodtaeeun** [comment]
Okay, I added my name and ID.

Any more things you need?

**Comment by Ahn-Ssu** [comment]
let me know your school email

**Comment by Ahn-Ssu** [comment]
in teammate.txt

**Comment by goodtaeeun** [comment]
Okay added my email.

**Pull request merged**
